export let ColorLevel1 = /** @type {const} */ ({
  Pink: 'Pink',
  Red: 'Red',
  Orange: 'Orange',
  Brown: 'Brown',
  Yellow: 'Yellow',
  Olive: 'Olive',
  YellowGreen: 'YellowGreen',
  Green: 'Green',
  Blue: 'Blue',
  Purple: 'Purple',
  White: 'White',
  Gray: 'Gray',
  Black: 'Black',
})

export let ColorLevel2 = /** @type {const} */ ({
  Pink: 'Pink',
  YellowishPink: 'YellowishPink',
  PurplishPink: 'PurplishPink',
  Red: 'Red',
  PurplishRed: 'PurplishRed',
  ReddishOrange: 'ReddishOrange',
  Orange: 'Orange',
  ReddishBrown: 'ReddishBrown',
  Brown: 'Brown',
  YellowishBrown: 'YellowishBrown',
  OrangeYellow: 'OrangeYellow',
  Yellow: 'Yellow',
  GreenishYellow: 'GreenishYellow',
  OliveBrown: 'OliveBrown',
  Olive: 'Olive',
  OliveGreen: 'OliveGreen',
  YellowGreen: 'YellowGreen',
  YellowishGreen: 'YellowishGreen',
  Green: 'Green',
  BluishGreen: 'BluishGreen',
  GreenishBlue: 'GreenishBlue',
  Blue: 'Blue',
  PurplishBlue: 'PurplishBlue',
  Violet: 'Violet',
  Purple: 'Purple',
  ReddishPurple: 'ReddishPurple',
  White: 'White',
  Gray: 'Gray',
  Black: 'Black',
})

export let ColorLevel3 = /** @type {const} */ ({
  VividPink: 'VividPink',
  StrongPink: 'StrongPink',
  DeepPink: 'DeepPink',
  LightPink: 'LightPink',
  ModeratePink: 'ModeratePink',
  DarkPink: 'DarkPink',
  PalePink: 'PalePink',
  GrayishPink: 'GrayishPink',
  PinkishWhite: 'PinkishWhite',
  PinkishGray: 'PinkishGray',
  VividYellowishPink: 'VividYellowishPink',
  StrongYellowishPink: 'StrongYellowishPink',
  DeepYellowishPink: 'DeepYellowishPink',
  LightYellowishPink: 'LightYellowishPink',
  ModerateYellowishPink: 'ModerateYellowishPink',
  DarkYellowishPink: 'DarkYellowishPink',
  PaleYellowishPink: 'PaleYellowishPink',
  GrayishYellowishPink: 'GrayishYellowishPink',
  BrownishPink: 'BrownishPink',
  BrilliantPurplishPink: 'BrilliantPurplishPink',
  StrongPurplishPink: 'StrongPurplishPink',
  DeepPurplishPink: 'DeepPurplishPink',
  LightPurplishPink: 'LightPurplishPink',
  ModeratePurplishPink: 'ModeratePurplishPink',
  DarkPurplishPink: 'DarkPurplishPink',
  PalePurplishPink: 'PalePurplishPink',
  GrayishPurplishPink: 'GrayishPurplishPink',
  VividRed: 'VividRed',
  StrongRed: 'StrongRed',
  DeepRed: 'DeepRed',
  VeryDeepRed: 'VeryDeepRed',
  ModerateRed: 'ModerateRed',
  DarkRed: 'DarkRed',
  VeryDarkRed: 'VeryDarkRed',
  LightGrayishRed: 'LightGrayishRed',
  GrayishRed: 'GrayishRed',
  DarkGrayishRed: 'DarkGrayishRed',
  BlackishRed: 'BlackishRed',
  ReddishGray: 'ReddishGray',
  DarkReddishGray: 'DarkReddishGray',
  ReddishBlack: 'ReddishBlack',
  VividPurplishRed: 'VividPurplishRed',
  StrongPurplishRed: 'StrongPurplishRed',
  DeepPurplishRed: 'DeepPurplishRed',
  VeryDeepPurplishRed: 'VeryDeepPurplishRed',
  ModeratePurplishRed: 'ModeratePurplishRed',
  DarkPurplishRed: 'DarkPurplishRed',
  VeryDarkPurplishRed: 'VeryDarkPurplishRed',
  LightGrayishPurplishRed: 'LightGrayishPurplishRed',
  GrayishPurplishRed: 'GrayishPurplishRed',
  VividReddishOrange: 'VividReddishOrange',
  StrongReddishOrange: 'StrongReddishOrange',
  DeepReddishOrange: 'DeepReddishOrange',
  ModerateReddishOrange: 'ModerateReddishOrange',
  DarkReddishOrange: 'DarkReddishOrange',
  GrayishReddishOrange: 'GrayishReddishOrange',
  VividOrange: 'VividOrange',
  BrilliantOrange: 'BrilliantOrange',
  StrongOrange: 'StrongOrange',
  DeepOrange: 'DeepOrange',
  LightOrange: 'LightOrange',
  ModerateOrange: 'ModerateOrange',
  BrownishOrange: 'BrownishOrange',
  StrongReddishBrown: 'StrongReddishBrown',
  DeepReddishBrown: 'DeepReddishBrown',
  LightReddishBrown: 'LightReddishBrown',
  ModerateReddishBrown: 'ModerateReddishBrown',
  DarkReddishBrown: 'DarkReddishBrown',
  LightGrayishReddishBrown: 'LightGrayishReddishBrown',
  GrayishReddishBrown: 'GrayishReddishBrown',
  DarkGrayishReddishBrown: 'DarkGrayishReddishBrown',
  StrongBrown: 'StrongBrown',
  DeepBrown: 'DeepBrown',
  LightBrown: 'LightBrown',
  ModerateBrown: 'ModerateBrown',
  DarkBrown: 'DarkBrown',
  LightGrayishBrown: 'LightGrayishBrown',
  GrayishBrown: 'GrayishBrown',
  DarkGrayishBrown: 'DarkGrayishBrown',
  LightBrownishGray: 'LightBrownishGray',
  BrownishGray: 'BrownishGray',
  BrownishBlack: 'BrownishBlack',
  StrongYellowishBrown: 'StrongYellowishBrown',
  DeepYellowishBrown: 'DeepYellowishBrown',
  LightYellowishBrown: 'LightYellowishBrown',
  ModerateYellowishBrown: 'ModerateYellowishBrown',
  DarkYellowishBrown: 'DarkYellowishBrown',
  LightGrayishYellowishBrown: 'LightGrayishYellowishBrown',
  GrayishYellowishBrown: 'GrayishYellowishBrown',
  DarkGrayishYellowishBrown: 'DarkGrayishYellowishBrown',
  VividOrangeYellow: 'VividOrangeYellow',
  BrilliantOrangeYellow: 'BrilliantOrangeYellow',
  StrongOrangeYellow: 'StrongOrangeYellow',
  DeepOrangeYellow: 'DeepOrangeYellow',
  LightOrangeYellow: 'LightOrangeYellow',
  ModerateOrangeYellow: 'ModerateOrangeYellow',
  DarkOrangeYellow: 'DarkOrangeYellow',
  PaleOrangeYellow: 'PaleOrangeYellow',
  VividYellow: 'VividYellow',
  BrilliantYellow: 'BrilliantYellow',
  StrongYellow: 'StrongYellow',
  DeepYellow: 'DeepYellow',
  LightYellow: 'LightYellow',
  ModerateYellow: 'ModerateYellow',
  DarkYellow: 'DarkYellow',
  PaleYellow: 'PaleYellow',
  GrayishYellow: 'GrayishYellow',
  DarkGrayishYellow: 'DarkGrayishYellow',
  YellowishWhite: 'YellowishWhite',
  YellowishGray: 'YellowishGray',
  VividGreenishYellow: 'VividGreenishYellow',
  BrilliantGreenishYellow: 'BrilliantGreenishYellow',
  StrongGreenishYellow: 'StrongGreenishYellow',
  DeepGreenishYellow: 'DeepGreenishYellow',
  LightGreenishYellow: 'LightGreenishYellow',
  ModerateGreenishYellow: 'ModerateGreenishYellow',
  DarkGreenishYellow: 'DarkGreenishYellow',
  PaleGreenishYellow: 'PaleGreenishYellow',
  GrayishGreenishYellow: 'GrayishGreenishYellow',
  LightOliveBrown: 'LightOliveBrown',
  ModerateOliveBrown: 'ModerateOliveBrown',
  DarkOliveBrown: 'DarkOliveBrown',
  LightOlive: 'LightOlive',
  ModerateOlive: 'ModerateOlive',
  DarkOlive: 'DarkOlive',
  LightGrayishOlive: 'LightGrayishOlive',
  GrayishOlive: 'GrayishOlive',
  DarkGrayishOlive: 'DarkGrayishOlive',
  LightOliveGray: 'LightOliveGray',
  OliveGray: 'OliveGray',
  OliveBlack: 'OliveBlack',
  StrongOliveGreen: 'StrongOliveGreen',
  DeepOliveGreen: 'DeepOliveGreen',
  ModerateOliveGreen: 'ModerateOliveGreen',
  DarkOliveGreen: 'DarkOliveGreen',
  GrayishOliveGreen: 'GrayishOliveGreen',
  DarkGrayishOliveGreen: 'DarkGrayishOliveGreen',
  VividYellowGreen: 'VividYellowGreen',
  BrilliantYellowGreen: 'BrilliantYellowGreen',
  StrongYellowGreen: 'StrongYellowGreen',
  DeepYellowGreen: 'DeepYellowGreen',
  LightYellowGreen: 'LightYellowGreen',
  ModerateYellowGreen: 'ModerateYellowGreen',
  PaleYellowGreen: 'PaleYellowGreen',
  GrayishYellowGreen: 'GrayishYellowGreen',
  VividYellowishGreen: 'VividYellowishGreen',
  BrilliantYellowishGreen: 'BrilliantYellowishGreen',
  StrongYellowishGreen: 'StrongYellowishGreen',
  DeepYellowishGreen: 'DeepYellowishGreen',
  VeryDeepYellowishGreen: 'VeryDeepYellowishGreen',
  VeryLightYellowishGreen: 'VeryLightYellowishGreen',
  LightYellowishGreen: 'LightYellowishGreen',
  ModerateYellowishGreen: 'ModerateYellowishGreen',
  DarkYellowishGreen: 'DarkYellowishGreen',
  VeryDarkYellowishGreen: 'VeryDarkYellowishGreen',
  VividGreen: 'VividGreen',
  BrilliantGreen: 'BrilliantGreen',
  StrongGreen: 'StrongGreen',
  DeepGreen: 'DeepGreen',
  VeryLightGreen: 'VeryLightGreen',
  LightGreen: 'LightGreen',
  ModerateGreen: 'ModerateGreen',
  DarkGreen: 'DarkGreen',
  VeryDarkGreen: 'VeryDarkGreen',
  VeryPaleGreen: 'VeryPaleGreen',
  PaleGreen: 'PaleGreen',
  GrayishGreen: 'GrayishGreen',
  DarkGrayishGreen: 'DarkGrayishGreen',
  BlackishGreen: 'BlackishGreen',
  GreenishWhite: 'GreenishWhite',
  LightGreenishGray: 'LightGreenishGray',
  GreenishGray: 'GreenishGray',
  DarkGreenishGray: 'DarkGreenishGray',
  GreenishBlack: 'GreenishBlack',
  VividBluishGreen: 'VividBluishGreen',
  BrilliantBluishGreen: 'BrilliantBluishGreen',
  StrongBluishGreen: 'StrongBluishGreen',
  DeepBluishGreen: 'DeepBluishGreen',
  VeryLightBluishGreen: 'VeryLightBluishGreen',
  LightBluishGreen: 'LightBluishGreen',
  ModerateBluishGreen: 'ModerateBluishGreen',
  DarkBluishGreen: 'DarkBluishGreen',
  VeryDarkBluishGreen: 'VeryDarkBluishGreen',
  VividGreenishBlue: 'VividGreenishBlue',
  BrilliantGreenishBlue: 'BrilliantGreenishBlue',
  StrongGreenishBlue: 'StrongGreenishBlue',
  DeepGreenishBlue: 'DeepGreenishBlue',
  VeryLightGreenishBlue: 'VeryLightGreenishBlue',
  LightGreenishBlue: 'LightGreenishBlue',
  ModerateGreenishBlue: 'ModerateGreenishBlue',
  DarkGreenishBlue: 'DarkGreenishBlue',
  VeryDarkGreenishBlue: 'VeryDarkGreenishBlue',
  VividBlue: 'VividBlue',
  BrilliantBlue: 'BrilliantBlue',
  StrongBlue: 'StrongBlue',
  DeepBlue: 'DeepBlue',
  VeryLightBlue: 'VeryLightBlue',
  LightBlue: 'LightBlue',
  ModerateBlue: 'ModerateBlue',
  DarkBlue: 'DarkBlue',
  VeryPaleBlue: 'VeryPaleBlue',
  PaleBlue: 'PaleBlue',
  GrayishBlue: 'GrayishBlue',
  DarkGrayishBlue: 'DarkGrayishBlue',
  BlackishBlue: 'BlackishBlue',
  BluishWhite: 'BluishWhite',
  LightBluishGray: 'LightBluishGray',
  BluishGray: 'BluishGray',
  DarkBluishGray: 'DarkBluishGray',
  BluishBlack: 'BluishBlack',
  VividPurplishBlue: 'VividPurplishBlue',
  BrilliantPurplishBlue: 'BrilliantPurplishBlue',
  StrongPurplishBlue: 'StrongPurplishBlue',
  DeepPurplishBlue: 'DeepPurplishBlue',
  VeryLightPurplishBlue: 'VeryLightPurplishBlue',
  LightPurplishBlue: 'LightPurplishBlue',
  ModeratePurplishBlue: 'ModeratePurplishBlue',
  DarkPurplishBlue: 'DarkPurplishBlue',
  VeryPalePurplishBlue: 'VeryPalePurplishBlue',
  PalePurplishBlue: 'PalePurplishBlue',
  GrayishPurplishBlue: 'GrayishPurplishBlue',
  VividViolet: 'VividViolet',
  BrilliantViolet: 'BrilliantViolet',
  StrongViolet: 'StrongViolet',
  DeepViolet: 'DeepViolet',
  VeryLightViolet: 'VeryLightViolet',
  LightViolet: 'LightViolet',
  ModerateViolet: 'ModerateViolet',
  DarkViolet: 'DarkViolet',
  VeryPaleViolet: 'VeryPaleViolet',
  PaleViolet: 'PaleViolet',
  GrayishViolet: 'GrayishViolet',
  VividPurple: 'VividPurple',
  BrilliantPurple: 'BrilliantPurple',
  StrongPurple: 'StrongPurple',
  DeepPurple: 'DeepPurple',
  VeryDeepPurple: 'VeryDeepPurple',
  VeryLightPurple: 'VeryLightPurple',
  LightPurple: 'LightPurple',
  ModeratePurple: 'ModeratePurple',
  DarkPurple: 'DarkPurple',
  VeryDarkPurple: 'VeryDarkPurple',
  VeryPalePurple: 'VeryPalePurple',
  PalePurple: 'PalePurple',
  GrayishPurple: 'GrayishPurple',
  DarkGrayishPurple: 'DarkGrayishPurple',
  BlackishPurple: 'BlackishPurple',
  PurplishWhite: 'PurplishWhite',
  LightPurplishGray: 'LightPurplishGray',
  PurplishGray: 'PurplishGray',
  DarkPurplishGray: 'DarkPurplishGray',
  PurplishBlack: 'PurplishBlack',
  VividReddishPurple: 'VividReddishPurple',
  StrongReddishPurple: 'StrongReddishPurple',
  DeepReddishPurple: 'DeepReddishPurple',
  VeryDeepReddishPurple: 'VeryDeepReddishPurple',
  LightReddishPurple: 'LightReddishPurple',
  ModerateReddishPurple: 'ModerateReddishPurple',
  DarkReddishPurple: 'DarkReddishPurple',
  VeryDarkReddishPurple: 'VeryDarkReddishPurple',
  PaleReddishPurple: 'PaleReddishPurple',
  GrayishReddishPurple: 'GrayishReddishPurple',
  White: 'White',
  LightGray: 'LightGray',
  MediumGray: 'MediumGray',
  DarkGray: 'DarkGray',
  Black: 'Black',
})

export let ColorLevel2Parent = /** @type {const} */ ({
  [ColorLevel2.Pink]: ColorLevel1.Pink,
  [ColorLevel2.YellowishPink]: ColorLevel1.Pink,
  [ColorLevel2.PurplishPink]: ColorLevel1.Pink,
  [ColorLevel2.Red]: ColorLevel1.Red,
  [ColorLevel2.PurplishRed]: ColorLevel1.Red,
  [ColorLevel2.ReddishOrange]: ColorLevel1.Orange,
  [ColorLevel2.Orange]: ColorLevel1.Orange,
  [ColorLevel2.ReddishBrown]: ColorLevel1.Brown,
  [ColorLevel2.Brown]: ColorLevel1.Brown,
  [ColorLevel2.YellowishBrown]: ColorLevel1.Brown,
  [ColorLevel2.OrangeYellow]: ColorLevel1.Yellow,
  [ColorLevel2.Yellow]: ColorLevel1.Yellow,
  [ColorLevel2.GreenishYellow]: ColorLevel1.Yellow,
  [ColorLevel2.OliveBrown]: ColorLevel1.Olive,
  [ColorLevel2.Olive]: ColorLevel1.Olive,
  [ColorLevel2.OliveGreen]: ColorLevel1.Olive,
  [ColorLevel2.YellowGreen]: ColorLevel1.YellowGreen,
  [ColorLevel2.YellowishGreen]: ColorLevel1.Green,
  [ColorLevel2.Green]: ColorLevel1.Green,
  [ColorLevel2.BluishGreen]: ColorLevel1.Green,
  [ColorLevel2.GreenishBlue]: ColorLevel1.Blue,
  [ColorLevel2.Blue]: ColorLevel1.Blue,
  [ColorLevel2.PurplishBlue]: ColorLevel1.Blue,
  [ColorLevel2.Violet]: ColorLevel1.Purple,
  [ColorLevel2.Purple]: ColorLevel1.Purple,
  [ColorLevel2.ReddishPurple]: ColorLevel1.Purple,
  [ColorLevel2.White]: ColorLevel1.White,
  [ColorLevel2.Gray]: ColorLevel1.Gray,
  [ColorLevel2.Black]: ColorLevel1.Black,
})

export let ColorLevel3Parent = /** @type {const} */ ({
  [ColorLevel3.VividPink]: ColorLevel2.Pink,
  [ColorLevel3.StrongPink]: ColorLevel2.Pink,
  [ColorLevel3.DeepPink]: ColorLevel2.Pink,
  [ColorLevel3.LightPink]: ColorLevel2.Pink,
  [ColorLevel3.ModeratePink]: ColorLevel2.Pink,
  [ColorLevel3.DarkPink]: ColorLevel2.Pink,
  [ColorLevel3.PalePink]: ColorLevel2.Pink,
  [ColorLevel3.GrayishPink]: ColorLevel2.Pink,
  [ColorLevel3.PinkishWhite]: ColorLevel2.Pink,
  [ColorLevel3.PinkishGray]: ColorLevel2.Pink,
  [ColorLevel3.VividYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.StrongYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.DeepYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.LightYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.ModerateYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.DarkYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.PaleYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.GrayishYellowishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.BrownishPink]: ColorLevel2.YellowishPink,
  [ColorLevel3.BrilliantPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.StrongPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.DeepPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.LightPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.ModeratePurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.DarkPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.PalePurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.GrayishPurplishPink]: ColorLevel2.PurplishPink,
  [ColorLevel3.VividRed]: ColorLevel2.Red,
  [ColorLevel3.StrongRed]: ColorLevel2.Red,
  [ColorLevel3.DeepRed]: ColorLevel2.Red,
  [ColorLevel3.VeryDeepRed]: ColorLevel2.Red,
  [ColorLevel3.ModerateRed]: ColorLevel2.Red,
  [ColorLevel3.DarkRed]: ColorLevel2.Red,
  [ColorLevel3.VeryDarkRed]: ColorLevel2.Red,
  [ColorLevel3.LightGrayishRed]: ColorLevel2.Red,
  [ColorLevel3.GrayishRed]: ColorLevel2.Red,
  [ColorLevel3.DarkGrayishRed]: ColorLevel2.Red,
  [ColorLevel3.BlackishRed]: ColorLevel2.Red,
  [ColorLevel3.ReddishGray]: ColorLevel2.Red,
  [ColorLevel3.DarkReddishGray]: ColorLevel2.Red,
  [ColorLevel3.ReddishBlack]: ColorLevel2.Red,
  [ColorLevel3.VividPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.StrongPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.DeepPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.VeryDeepPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.ModeratePurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.DarkPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.VeryDarkPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.LightGrayishPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.GrayishPurplishRed]: ColorLevel2.PurplishRed,
  [ColorLevel3.VividReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.StrongReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.DeepReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.ModerateReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.DarkReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.GrayishReddishOrange]: ColorLevel2.ReddishOrange,
  [ColorLevel3.VividOrange]: ColorLevel2.Orange,
  [ColorLevel3.BrilliantOrange]: ColorLevel2.Orange,
  [ColorLevel3.StrongOrange]: ColorLevel2.Orange,
  [ColorLevel3.DeepOrange]: ColorLevel2.Orange,
  [ColorLevel3.LightOrange]: ColorLevel2.Orange,
  [ColorLevel3.ModerateOrange]: ColorLevel2.Orange,
  [ColorLevel3.BrownishOrange]: ColorLevel2.Orange,
  [ColorLevel3.StrongReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.DeepReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.LightReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.ModerateReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.DarkReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.LightGrayishReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.GrayishReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.DarkGrayishReddishBrown]: ColorLevel2.ReddishBrown,
  [ColorLevel3.StrongBrown]: ColorLevel2.Brown,
  [ColorLevel3.DeepBrown]: ColorLevel2.Brown,
  [ColorLevel3.LightBrown]: ColorLevel2.Brown,
  [ColorLevel3.ModerateBrown]: ColorLevel2.Brown,
  [ColorLevel3.DarkBrown]: ColorLevel2.Brown,
  [ColorLevel3.LightGrayishBrown]: ColorLevel2.Brown,
  [ColorLevel3.GrayishBrown]: ColorLevel2.Brown,
  [ColorLevel3.DarkGrayishBrown]: ColorLevel2.Brown,
  [ColorLevel3.LightBrownishGray]: ColorLevel2.Brown,
  [ColorLevel3.BrownishGray]: ColorLevel2.Brown,
  [ColorLevel3.BrownishBlack]: ColorLevel2.Brown,
  [ColorLevel3.StrongYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.DeepYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.LightYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.ModerateYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.DarkYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.LightGrayishYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.GrayishYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.DarkGrayishYellowishBrown]: ColorLevel2.YellowishBrown,
  [ColorLevel3.VividOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.BrilliantOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.StrongOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.DeepOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.LightOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.ModerateOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.DarkOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.PaleOrangeYellow]: ColorLevel2.OrangeYellow,
  [ColorLevel3.VividYellow]: ColorLevel2.Yellow,
  [ColorLevel3.BrilliantYellow]: ColorLevel2.Yellow,
  [ColorLevel3.StrongYellow]: ColorLevel2.Yellow,
  [ColorLevel3.DeepYellow]: ColorLevel2.Yellow,
  [ColorLevel3.LightYellow]: ColorLevel2.Yellow,
  [ColorLevel3.ModerateYellow]: ColorLevel2.Yellow,
  [ColorLevel3.DarkYellow]: ColorLevel2.Yellow,
  [ColorLevel3.PaleYellow]: ColorLevel2.Yellow,
  [ColorLevel3.GrayishYellow]: ColorLevel2.Yellow,
  [ColorLevel3.DarkGrayishYellow]: ColorLevel2.Yellow,
  [ColorLevel3.YellowishWhite]: ColorLevel2.Yellow,
  [ColorLevel3.YellowishGray]: ColorLevel2.Yellow,
  [ColorLevel3.VividGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.BrilliantGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.StrongGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.DeepGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.LightGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.ModerateGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.DarkGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.PaleGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.GrayishGreenishYellow]: ColorLevel2.GreenishYellow,
  [ColorLevel3.LightOliveBrown]: ColorLevel2.OliveBrown,
  [ColorLevel3.ModerateOliveBrown]: ColorLevel2.OliveBrown,
  [ColorLevel3.DarkOliveBrown]: ColorLevel2.OliveBrown,
  [ColorLevel3.LightOlive]: ColorLevel2.Olive,
  [ColorLevel3.ModerateOlive]: ColorLevel2.Olive,
  [ColorLevel3.DarkOlive]: ColorLevel2.Olive,
  [ColorLevel3.LightGrayishOlive]: ColorLevel2.Olive,
  [ColorLevel3.GrayishOlive]: ColorLevel2.Olive,
  [ColorLevel3.DarkGrayishOlive]: ColorLevel2.Olive,
  [ColorLevel3.LightOliveGray]: ColorLevel2.Olive,
  [ColorLevel3.OliveGray]: ColorLevel2.Olive,
  [ColorLevel3.OliveBlack]: ColorLevel2.Olive,
  [ColorLevel3.StrongOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.DeepOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.ModerateOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.DarkOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.GrayishOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.DarkGrayishOliveGreen]: ColorLevel2.OliveGreen,
  [ColorLevel3.VividYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.BrilliantYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.StrongYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.DeepYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.LightYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.ModerateYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.PaleYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.GrayishYellowGreen]: ColorLevel2.YellowGreen,
  [ColorLevel3.VividYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.BrilliantYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.StrongYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.DeepYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.VeryDeepYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.VeryLightYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.LightYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.ModerateYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.DarkYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.VeryDarkYellowishGreen]: ColorLevel2.YellowishGreen,
  [ColorLevel3.VividGreen]: ColorLevel2.Green,
  [ColorLevel3.BrilliantGreen]: ColorLevel2.Green,
  [ColorLevel3.StrongGreen]: ColorLevel2.Green,
  [ColorLevel3.DeepGreen]: ColorLevel2.Green,
  [ColorLevel3.VeryLightGreen]: ColorLevel2.Green,
  [ColorLevel3.LightGreen]: ColorLevel2.Green,
  [ColorLevel3.ModerateGreen]: ColorLevel2.Green,
  [ColorLevel3.DarkGreen]: ColorLevel2.Green,
  [ColorLevel3.VeryDarkGreen]: ColorLevel2.Green,
  [ColorLevel3.VeryPaleGreen]: ColorLevel2.Green,
  [ColorLevel3.PaleGreen]: ColorLevel2.Green,
  [ColorLevel3.GrayishGreen]: ColorLevel2.Green,
  [ColorLevel3.DarkGrayishGreen]: ColorLevel2.Green,
  [ColorLevel3.BlackishGreen]: ColorLevel2.Green,
  [ColorLevel3.GreenishWhite]: ColorLevel2.Green,
  [ColorLevel3.LightGreenishGray]: ColorLevel2.Green,
  [ColorLevel3.GreenishGray]: ColorLevel2.Green,
  [ColorLevel3.DarkGreenishGray]: ColorLevel2.Green,
  [ColorLevel3.GreenishBlack]: ColorLevel2.Green,
  [ColorLevel3.VividBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.BrilliantBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.StrongBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.DeepBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.VeryLightBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.LightBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.ModerateBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.DarkBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.VeryDarkBluishGreen]: ColorLevel2.BluishGreen,
  [ColorLevel3.VividGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.BrilliantGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.StrongGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.DeepGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.VeryLightGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.LightGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.ModerateGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.DarkGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.VeryDarkGreenishBlue]: ColorLevel2.GreenishBlue,
  [ColorLevel3.VividBlue]: ColorLevel2.Blue,
  [ColorLevel3.BrilliantBlue]: ColorLevel2.Blue,
  [ColorLevel3.StrongBlue]: ColorLevel2.Blue,
  [ColorLevel3.DeepBlue]: ColorLevel2.Blue,
  [ColorLevel3.VeryLightBlue]: ColorLevel2.Blue,
  [ColorLevel3.LightBlue]: ColorLevel2.Blue,
  [ColorLevel3.ModerateBlue]: ColorLevel2.Blue,
  [ColorLevel3.DarkBlue]: ColorLevel2.Blue,
  [ColorLevel3.VeryPaleBlue]: ColorLevel2.Blue,
  [ColorLevel3.PaleBlue]: ColorLevel2.Blue,
  [ColorLevel3.GrayishBlue]: ColorLevel2.Blue,
  [ColorLevel3.DarkGrayishBlue]: ColorLevel2.Blue,
  [ColorLevel3.BlackishBlue]: ColorLevel2.Blue,
  [ColorLevel3.BluishWhite]: ColorLevel2.Blue,
  [ColorLevel3.LightBluishGray]: ColorLevel2.Blue,
  [ColorLevel3.BluishGray]: ColorLevel2.Blue,
  [ColorLevel3.DarkBluishGray]: ColorLevel2.Blue,
  [ColorLevel3.BluishBlack]: ColorLevel2.Blue,
  [ColorLevel3.VividPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.BrilliantPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.StrongPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.DeepPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.VeryLightPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.LightPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.ModeratePurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.DarkPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.VeryPalePurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.PalePurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.GrayishPurplishBlue]: ColorLevel2.PurplishBlue,
  [ColorLevel3.VividViolet]: ColorLevel2.Violet,
  [ColorLevel3.BrilliantViolet]: ColorLevel2.Violet,
  [ColorLevel3.StrongViolet]: ColorLevel2.Violet,
  [ColorLevel3.DeepViolet]: ColorLevel2.Violet,
  [ColorLevel3.VeryLightViolet]: ColorLevel2.Violet,
  [ColorLevel3.LightViolet]: ColorLevel2.Violet,
  [ColorLevel3.ModerateViolet]: ColorLevel2.Violet,
  [ColorLevel3.DarkViolet]: ColorLevel2.Violet,
  [ColorLevel3.VeryPaleViolet]: ColorLevel2.Violet,
  [ColorLevel3.PaleViolet]: ColorLevel2.Violet,
  [ColorLevel3.GrayishViolet]: ColorLevel2.Violet,
  [ColorLevel3.VividPurple]: ColorLevel2.Purple,
  [ColorLevel3.BrilliantPurple]: ColorLevel2.Purple,
  [ColorLevel3.StrongPurple]: ColorLevel2.Purple,
  [ColorLevel3.DeepPurple]: ColorLevel2.Purple,
  [ColorLevel3.VeryDeepPurple]: ColorLevel2.Purple,
  [ColorLevel3.VeryLightPurple]: ColorLevel2.Purple,
  [ColorLevel3.LightPurple]: ColorLevel2.Purple,
  [ColorLevel3.ModeratePurple]: ColorLevel2.Purple,
  [ColorLevel3.DarkPurple]: ColorLevel2.Purple,
  [ColorLevel3.VeryDarkPurple]: ColorLevel2.Purple,
  [ColorLevel3.VeryPalePurple]: ColorLevel2.Purple,
  [ColorLevel3.PalePurple]: ColorLevel2.Purple,
  [ColorLevel3.GrayishPurple]: ColorLevel2.Purple,
  [ColorLevel3.DarkGrayishPurple]: ColorLevel2.Purple,
  [ColorLevel3.BlackishPurple]: ColorLevel2.Purple,
  [ColorLevel3.PurplishWhite]: ColorLevel2.Purple,
  [ColorLevel3.LightPurplishGray]: ColorLevel2.Purple,
  [ColorLevel3.PurplishGray]: ColorLevel2.Purple,
  [ColorLevel3.DarkPurplishGray]: ColorLevel2.Purple,
  [ColorLevel3.PurplishBlack]: ColorLevel2.Purple,
  [ColorLevel3.VividReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.StrongReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.DeepReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.VeryDeepReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.LightReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.ModerateReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.DarkReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.VeryDarkReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.PaleReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.GrayishReddishPurple]: ColorLevel2.ReddishPurple,
  [ColorLevel3.White]: ColorLevel2.White,
  [ColorLevel3.LightGray]: ColorLevel2.Gray,
  [ColorLevel3.MediumGray]: ColorLevel2.Gray,
  [ColorLevel3.DarkGray]: ColorLevel2.Gray,
  [ColorLevel3.Black]: ColorLevel2.Black,
})

export let ColorCentroid = /** @type {const} */ ([
  { l: 0.736, a: 0.1594, b: 0.0283, color: ColorLevel3.VividPink },
  { l: 0.7609, a: 0.1215, b: 0.0205, color: ColorLevel3.StrongPink },
  { l: 0.6777, a: 0.1533, b: 0.0292, color: ColorLevel3.DeepPink },
  { l: 0.8671, a: 0.0618, b: 0.0049, color: ColorLevel3.LightPink },
  { l: 0.7782, a: 0.0752, b: 0.0098, color: ColorLevel3.ModeratePink },
  { l: 0.6738, a: 0.0849, b: 0.0152, color: ColorLevel3.DarkPink },
  { l: 0.8888, a: 0.0361, b: -0.004, color: ColorLevel3.PalePink },
  { l: 0.7767, a: 0.0371, b: -0.0026, color: ColorLevel3.GrayishPink },
  { l: 0.9143, a: 0.0219, b: -0.0043, color: ColorLevel3.PinkishWhite },
  { l: 0.7926, a: 0.0213, b: -0.0035, color: ColorLevel3.PinkishGray },
  { l: 0.5615, a: 0.1996, b: 0.0733, color: ColorLevel3.VividRed },
  { l: 0.5417, a: 0.1679, b: 0.0484, color: ColorLevel3.StrongRed },
  { l: 0.4054, a: 0.1436, b: 0.04, color: ColorLevel3.DeepRed },
  { l: 0.3091, a: 0.1159, b: 0.0156, color: ColorLevel3.VeryDeepRed },
  { l: 0.5454, a: 0.1306, b: 0.0369, color: ColorLevel3.ModerateRed },
  { l: 0.388, a: 0.1097, b: 0.0236, color: ColorLevel3.DarkRed },
  { l: 0.2793, a: 0.0861, b: -0.0002, color: ColorLevel3.VeryDarkRed },
  { l: 0.6704, a: 0.0533, b: 0.0104, color: ColorLevel3.LightGrayishRed },
  { l: 0.5454, a: 0.0751, b: 0.0194, color: ColorLevel3.GrayishRed },
  { l: 0.3738, a: 0.0393, b: 0.0031, color: ColorLevel3.DarkGrayishRed },
  { l: 0.2724, a: 0.0294, b: -0.0013, color: ColorLevel3.BlackishRed },
  { l: 0.6202, a: 0.0219, b: -0.0008, color: ColorLevel3.ReddishGray },
  { l: 0.4407, a: 0.0214, b: -0.0015, color: ColorLevel3.DarkReddishGray },
  { l: 0.2819, a: 0.0168, b: -0.004, color: ColorLevel3.ReddishBlack },
  { l: 0.7326, a: 0.1321, b: 0.0946, color: ColorLevel3.VividYellowishPink },
  { l: 0.7563, a: 0.1088, b: 0.0625, color: ColorLevel3.StrongYellowishPink },
  { l: 0.6769, a: 0.161, b: 0.0639, color: ColorLevel3.DeepYellowishPink },
  { l: 0.8627, a: 0.0512, b: 0.0366, color: ColorLevel3.LightYellowishPink },
  { l: 0.778, a: 0.0619, b: 0.041, color: ColorLevel3.ModerateYellowishPink },
  { l: 0.6753, a: 0.0848, b: 0.0333, color: ColorLevel3.DarkYellowishPink },
  { l: 0.8913, a: 0.0312, b: 0.0128, color: ColorLevel3.PaleYellowishPink },
  { l: 0.7716, a: 0.0344, b: 0.0112, color: ColorLevel3.GrayishYellowishPink },
  { l: 0.7761, a: 0.0278, b: 0.0206, color: ColorLevel3.BrownishPink },
  { l: 0.613, a: 0.1802, b: 0.1146, color: ColorLevel3.VividReddishOrange },
  { l: 0.6325, a: 0.1342, b: 0.0975, color: ColorLevel3.StrongReddishOrange },
  { l: 0.5057, a: 0.1373, b: 0.0913, color: ColorLevel3.DeepReddishOrange },
  { l: 0.633, a: 0.1092, b: 0.074, color: ColorLevel3.ModerateReddishOrange },
  { l: 0.5016, a: 0.1122, b: 0.0749, color: ColorLevel3.DarkReddishOrange },
  { l: 0.6307, a: 0.0745, b: 0.0501, color: ColorLevel3.GrayishReddishOrange },
  { l: 0.4164, a: 0.1273, b: 0.0761, color: ColorLevel3.StrongReddishBrown },
  { l: 0.3221, a: 0.1037, b: 0.0483, color: ColorLevel3.DeepReddishBrown },
  { l: 0.6279, a: 0.0565, b: 0.03, color: ColorLevel3.LightReddishBrown },
  { l: 0.4503, a: 0.0733, b: 0.0388, color: ColorLevel3.ModerateReddishBrown },
  { l: 0.2909, a: 0.0592, b: 0.0219, color: ColorLevel3.DarkReddishBrown },
  { l: 0.6244, a: 0.0344, b: 0.019, color: ColorLevel3.LightGrayishReddishBrown },
  { l: 0.4531, a: 0.039, b: 0.0166, color: ColorLevel3.GrayishReddishBrown },
  { l: 0.3136, a: 0.0374, b: 0.0114, color: ColorLevel3.DarkGrayishReddishBrown },
  { l: 0.706, a: 0.1184, b: 0.141, color: ColorLevel3.VividOrange },
  { l: 0.7062, a: 0.0912, b: 0.1316, color: ColorLevel3.StrongOrange },
  { l: 0.5967, a: 0.0927, b: 0.1159, color: ColorLevel3.DeepOrange },
  { l: 0.8167, a: 0.0671, b: 0.0838, color: ColorLevel3.LightOrange },
  { l: 0.7168, a: 0.0741, b: 0.0919, color: ColorLevel3.ModerateOrange },
  { l: 0.5867, a: 0.0721, b: 0.0928, color: ColorLevel3.BrownishOrange },
  { l: 0.4678, a: 0.072, b: 0.0843, color: ColorLevel3.StrongBrown },
  { l: 0.3133, a: 0.0756, b: 0.0569, color: ColorLevel3.DeepBrown },
  { l: 0.6291, a: 0.0477, b: 0.053, color: ColorLevel3.LightBrown },
  { l: 0.4497, a: 0.0437, b: 0.0436, color: ColorLevel3.ModerateBrown },
  { l: 0.2926, a: 0.0432, b: 0.0406, color: ColorLevel3.DarkBrown },
  { l: 0.6179, a: 0.0264, b: 0.0238, color: ColorLevel3.LightGrayishBrown },
  { l: 0.4506, a: 0.0276, b: 0.0207, color: ColorLevel3.GrayishBrown },
  { l: 0.3129, a: 0.0234, b: 0.0151, color: ColorLevel3.DarkGrayishBrown },
  { l: 0.6207, a: 0.0182, b: 0.0073, color: ColorLevel3.LightBrownishGray },
  { l: 0.4522, a: 0.0173, b: 0.0072, color: ColorLevel3.BrownishGray },
  { l: 0.2585, a: 0.0131, b: 0.01, color: ColorLevel3.BrownishBlack },
  { l: 0.8419, a: 0.0313, b: 0.1408, color: ColorLevel3.BrilliantOrangeYellow },
  { l: 0.7687, a: 0.0479, b: 0.1492, color: ColorLevel3.StrongOrangeYellow },
  { l: 0.6789, a: 0.0511, b: 0.1346, color: ColorLevel3.DeepOrangeYellow },
  { l: 0.8516, a: 0.0363, b: 0.1036, color: ColorLevel3.LightOrangeYellow },
  { l: 0.7746, a: 0.0433, b: 0.11, color: ColorLevel3.ModerateOrangeYellow },
  { l: 0.6675, a: 0.0419, b: 0.1108, color: ColorLevel3.DarkOrangeYellow },
  { l: 0.8532, a: 0.0308, b: 0.0544, color: ColorLevel3.PaleOrangeYellow },
  { l: 0.5605, a: 0.0397, b: 0.103, color: ColorLevel3.StrongYellowishBrown },
  { l: 0.4061, a: 0.0329, b: 0.0768, color: ColorLevel3.DeepYellowishBrown },
  { l: 0.7161, a: 0.0323, b: 0.0646, color: ColorLevel3.LightYellowishBrown },
  { l: 0.5373, a: 0.0286, b: 0.0547, color: ColorLevel3.ModerateYellowishBrown },
  { l: 0.3521, a: 0.0263, b: 0.0498, color: ColorLevel3.DarkYellowishBrown },
  { l: 0.7078, a: 0.0226, b: 0.0279, color: ColorLevel3.LightGrayishYellowishBrown },
  { l: 0.5376, a: 0.0203, b: 0.0255, color: ColorLevel3.GrayishYellowishBrown },
  { l: 0.3741, a: 0.0166, b: 0.0225, color: ColorLevel3.DarkGrayishYellowishBrown },
  { l: 0.8261, a: 0.0026, b: 0.1656, color: ColorLevel3.VividYellow },
  { l: 0.8646, a: -0.0019, b: 0.1475, color: ColorLevel3.BrilliantYellow },
  { l: 0.7691, a: 0.0031, b: 0.1436, color: ColorLevel3.StrongYellow },
  { l: 0.6706, a: 0.0065, b: 0.1319, color: ColorLevel3.DeepYellow },
  { l: 0.8758, a: 0.0059, b: 0.104, color: ColorLevel3.LightYellow },
  { l: 0.7691, a: 0.0086, b: 0.1031, color: ColorLevel3.ModerateYellow },
  { l: 0.6653, a: 0.0072, b: 0.1032, color: ColorLevel3.DarkYellow },
  { l: 0.8897, a: 0.011, b: 0.0544, color: ColorLevel3.PaleYellow },
  { l: 0.7706, a: 0.0099, b: 0.0569, color: ColorLevel3.GrayishYellow },
  { l: 0.6658, a: 0.0111, b: 0.064, color: ColorLevel3.DarkGrayishYellow },
  { l: 0.9143, a: 0.0138, b: 0.0113, color: ColorLevel3.YellowishWhite },
  { l: 0.7943, a: 0.011, b: 0.015, color: ColorLevel3.YellowishGray },
  { l: 0.5892, a: 0.0139, b: 0.0919, color: ColorLevel3.LightOliveBrown },
  { l: 0.4646, a: 0.0134, b: 0.0766, color: ColorLevel3.ModerateOliveBrown },
  { l: 0.309, a: 0.0134, b: 0.0485, color: ColorLevel3.DarkOliveBrown },
  { l: 0.8813, a: -0.046, b: 0.175, color: ColorLevel3.VividGreenishYellow },
  { l: 0.8805, a: -0.0366, b: 0.1488, color: ColorLevel3.BrilliantGreenishYellow },
  { l: 0.7691, a: -0.0379, b: 0.148, color: ColorLevel3.StrongGreenishYellow },
  { l: 0.6674, a: -0.0348, b: 0.1329, color: ColorLevel3.DeepGreenishYellow },
  { l: 0.889, a: -0.0201, b: 0.1027, color: ColorLevel3.LightGreenishYellow },
  { l: 0.764, a: -0.0231, b: 0.1072, color: ColorLevel3.ModerateGreenishYellow },
  { l: 0.6598, a: -0.0259, b: 0.1075, color: ColorLevel3.DarkGreenishYellow },
  { l: 0.8905, a: -0.0089, b: 0.0643, color: ColorLevel3.PaleGreenishYellow },
  { l: 0.7685, a: -0.0103, b: 0.0656, color: ColorLevel3.GrayishGreenishYellow },
  { l: 0.5867, a: -0.016, b: 0.0987, color: ColorLevel3.LightOlive },
  { l: 0.4619, a: -0.0131, b: 0.0813, color: ColorLevel3.ModerateOlive },
  { l: 0.3006, a: -0.0074, b: 0.0523, color: ColorLevel3.DarkOlive },
  { l: 0.6185, a: 0.0009, b: 0.0336, color: ColorLevel3.LightGrayishOlive },
  { l: 0.451, a: -0.0003, b: 0.0354, color: ColorLevel3.GrayishOlive },
  { l: 0.3087, a: -0.0034, b: 0.0334, color: ColorLevel3.DarkGrayishOlive },
  { l: 0.628, a: 0.0058, b: 0.0141, color: ColorLevel3.LightOliveGray },
  { l: 0.4395, a: 0.0056, b: 0.0135, color: ColorLevel3.OliveGray },
  { l: 0.2481, a: 0.0002, b: 0.0097, color: ColorLevel3.OliveBlack },
  { l: 0.8277, a: -0.117, b: 0.1626, color: ColorLevel3.VividYellowGreen },
  { l: 0.8588, a: -0.0755, b: 0.1271, color: ColorLevel3.BrilliantYellowGreen },
  { l: 0.6631, a: -0.08, b: 0.1215, color: ColorLevel3.StrongYellowGreen },
  { l: 0.4859, a: -0.0784, b: 0.095, color: ColorLevel3.DeepYellowGreen },
  { l: 0.8669, a: -0.0377, b: 0.0708, color: ColorLevel3.LightYellowGreen },
  { l: 0.6597, a: -0.0421, b: 0.0718, color: ColorLevel3.ModerateYellowGreen },
  { l: 0.8732, a: -0.0086, b: 0.0283, color: ColorLevel3.PaleYellowGreen },
  { l: 0.6778, a: -0.0122, b: 0.0276, color: ColorLevel3.GrayishYellowGreen },
  { l: 0.4037, a: -0.0789, b: 0.0803, color: ColorLevel3.StrongOliveGreen },
  { l: 0.4426, a: -0.0479, b: 0.0697, color: ColorLevel3.ModerateOliveGreen },
  { l: 0.2977, a: -0.0458, b: 0.0513, color: ColorLevel3.DarkOliveGreen },
  { l: 0.454, a: -0.0146, b: 0.0251, color: ColorLevel3.GrayishOliveGreen },
  { l: 0.3129, a: -0.0121, b: 0.0196, color: ColorLevel3.DarkGrayishOliveGreen },
  { l: 0.7717, a: -0.1822, b: 0.1371, color: ColorLevel3.VividYellowishGreen },
  { l: 0.8128, a: -0.1117, b: 0.079, color: ColorLevel3.BrilliantYellowishGreen },
  { l: 0.5993, a: -0.1193, b: 0.0774, color: ColorLevel3.StrongYellowishGreen },
  { l: 0.4597, a: -0.1091, b: 0.0792, color: ColorLevel3.DeepYellowishGreen },
  { l: 0.3304, a: -0.0838, b: 0.0625, color: ColorLevel3.VeryDeepYellowishGreen },
  { l: 0.9068, a: -0.0562, b: 0.0403, color: ColorLevel3.VeryLightYellowishGreen },
  { l: 0.785, a: -0.0603, b: 0.0425, color: ColorLevel3.LightYellowishGreen },
  { l: 0.6116, a: -0.062, b: 0.0412, color: ColorLevel3.ModerateYellowishGreen },
  { l: 0.4352, a: -0.0666, b: 0.0385, color: ColorLevel3.DarkYellowishGreen },
  { l: 0.2973, a: -0.0567, b: 0.0337, color: ColorLevel3.VeryDarkYellowishGreen },
  { l: 0.831, a: -0.1673, b: 0.0529, color: ColorLevel3.VividGreen },
  { l: 0.7726, a: -0.1309, b: 0.0301, color: ColorLevel3.BrilliantGreen },
  { l: 0.564, a: -0.1087, b: 0.0275, color: ColorLevel3.StrongGreen },
  { l: 0.8652, a: -0.0682, b: 0.0144, color: ColorLevel3.VeryLightGreen },
  { l: 0.696, a: -0.0707, b: 0.0144, color: ColorLevel3.LightGreen },
  { l: 0.519, a: -0.0761, b: 0.0131, color: ColorLevel3.ModerateGreen },
  { l: 0.3824, a: -0.0638, b: 0.0123, color: ColorLevel3.DarkGreen },
  { l: 0.273, a: -0.043, b: 0.0073, color: ColorLevel3.VeryDarkGreen },
  { l: 0.8709, a: -0.0197, b: -0.0017, color: ColorLevel3.VeryPaleGreen },
  { l: 0.7102, a: -0.0206, b: -0.0017, color: ColorLevel3.PaleGreen },
  { l: 0.5344, a: -0.0197, b: -0.001, color: ColorLevel3.GrayishGreen },
  { l: 0.3853, a: -0.0177, b: -0.0035, color: ColorLevel3.DarkGrayishGreen },
  { l: 0.2747, a: -0.0146, b: -0.0043, color: ColorLevel3.BlackishGreen },
  { l: 0.9121, a: -0.0009, b: -0.0045, color: ColorLevel3.GreenishWhite },
  { l: 0.7992, a: -0.0031, b: -0.0053, color: ColorLevel3.LightGreenishGray },
  { l: 0.6234, a: -0.0045, b: -0.0014, color: ColorLevel3.GreenishGray },
  { l: 0.4568, a: -0.0049, b: -0.0015, color: ColorLevel3.DarkGreenishGray },
  { l: 0.2636, a: -0.0069, b: -0.0021, color: ColorLevel3.GreenishBlack },
  { l: 0.8861, a: -0.1638, b: 0.0119, color: ColorLevel3.VividBluishGreen },
  { l: 0.7979, a: -0.1262, b: -0.0205, color: ColorLevel3.BrilliantBluishGreen },
  { l: 0.585, a: -0.1015, b: -0.0063, color: ColorLevel3.StrongBluishGreen },
  { l: 0.8617, a: -0.0701, b: -0.0185, color: ColorLevel3.VeryLightBluishGreen },
  { l: 0.6925, a: -0.0728, b: -0.0203, color: ColorLevel3.LightBluishGreen },
  { l: 0.532, a: -0.0734, b: -0.0214, color: ColorLevel3.ModerateBluishGreen },
  { l: 0.3792, a: -0.0522, b: -0.0176, color: ColorLevel3.DarkBluishGreen },
  { l: 0.2731, a: -0.0372, b: -0.012, color: ColorLevel3.VeryDarkBluishGreen },
  { l: 0.7392, a: -0.0951, b: -0.0824, color: ColorLevel3.BrilliantGreenishBlue },
  { l: 0.5786, a: -0.0711, b: -0.0857, color: ColorLevel3.StrongGreenishBlue },
  { l: 0.8405, a: -0.0543, b: -0.0518, color: ColorLevel3.VeryLightGreenishBlue },
  { l: 0.6972, a: -0.0548, b: -0.0565, color: ColorLevel3.LightGreenishBlue },
  { l: 0.5313, a: -0.0589, b: -0.06, color: ColorLevel3.ModerateGreenishBlue },
  { l: 0.3849, a: -0.0433, b: -0.0505, color: ColorLevel3.DarkGreenishBlue },
  { l: 0.2771, a: -0.0288, b: -0.0366, color: ColorLevel3.VeryDarkGreenishBlue },
  { l: 0.5135, a: -0.029, b: -0.1978, color: ColorLevel3.VividBlue },
  { l: 0.6777, a: -0.0544, b: -0.1363, color: ColorLevel3.BrilliantBlue },
  { l: 0.5312, a: -0.0375, b: -0.1393, color: ColorLevel3.StrongBlue },
  { l: 0.3328, a: -0.015, b: -0.122, color: ColorLevel3.DeepBlue },
  { l: 0.813, a: -0.0268, b: -0.0826, color: ColorLevel3.VeryLightBlue },
  { l: 0.7062, a: -0.0295, b: -0.0934, color: ColorLevel3.LightBlue },
  { l: 0.5073, a: -0.033, b: -0.0974, color: ColorLevel3.ModerateBlue },
  { l: 0.3234, a: -0.0186, b: -0.0725, color: ColorLevel3.DarkBlue },
  { l: 0.8599, a: -0.0069, b: -0.0396, color: ColorLevel3.VeryPaleBlue },
  { l: 0.7074, a: -0.0087, b: -0.0405, color: ColorLevel3.PaleBlue },
  { l: 0.5099, a: -0.0134, b: -0.0418, color: ColorLevel3.GrayishBlue },
  { l: 0.3625, a: -0.0095, b: -0.0297, color: ColorLevel3.DarkGrayishBlue },
  { l: 0.2632, a: -0.0038, b: -0.0245, color: ColorLevel3.BlackishBlue },
  { l: 0.9145, a: 0.0059, b: -0.0208, color: ColorLevel3.BluishWhite },
  { l: 0.7861, a: 0.0043, b: -0.0192, color: ColorLevel3.LightBluishGray },
  { l: 0.624, a: 0.0004, b: -0.0186, color: ColorLevel3.BluishGray },
  { l: 0.4463, a: -0.0001, b: -0.0187, color: ColorLevel3.DarkBluishGray },
  { l: 0.2727, a: -0.0007, b: -0.0137, color: ColorLevel3.BluishBlack },
  { l: 0.4617, a: 0.0273, b: -0.223, color: ColorLevel3.VividPurplishBlue },
  { l: 0.6593, a: 0.0191, b: -0.1319, color: ColorLevel3.BrilliantPurplishBlue },
  { l: 0.507, a: 0.0179, b: -0.142, color: ColorLevel3.StrongPurplishBlue },
  { l: 0.3259, a: 0.0181, b: -0.1179, color: ColorLevel3.DeepPurplishBlue },
  { l: 0.8203, a: 0.0102, b: -0.0788, color: ColorLevel3.VeryLightPurplishBlue },
  { l: 0.6725, a: 0.0117, b: -0.0856, color: ColorLevel3.LightPurplishBlue },
  { l: 0.4502, a: 0.018, b: -0.0904, color: ColorLevel3.ModeratePurplishBlue },
  { l: 0.274, a: 0.013, b: -0.0677, color: ColorLevel3.DarkPurplishBlue },
  { l: 0.8455, a: 0.01, b: -0.0535, color: ColorLevel3.VeryPalePurplishBlue },
  { l: 0.6698, a: 0.0095, b: -0.054, color: ColorLevel3.PalePurplishBlue },
  { l: 0.4323, a: 0.009, b: -0.059, color: ColorLevel3.GrayishPurplishBlue },
  { l: 0.5066, a: 0.106, b: -0.2021, color: ColorLevel3.VividViolet },
  { l: 0.6584, a: 0.0572, b: -0.1241, color: ColorLevel3.BrilliantViolet },
  { l: 0.4581, a: 0.0638, b: -0.1275, color: ColorLevel3.StrongViolet },
  { l: 0.3099, a: 0.0656, b: -0.116, color: ColorLevel3.DeepViolet },
  { l: 0.8226, a: 0.0376, b: -0.0788, color: ColorLevel3.VeryLightViolet },
  { l: 0.6766, a: 0.0386, b: -0.0829, color: ColorLevel3.LightViolet },
  { l: 0.4525, a: 0.044, b: -0.0866, color: ColorLevel3.ModerateViolet },
  { l: 0.3028, a: 0.0352, b: -0.0624, color: ColorLevel3.DarkViolet },
  { l: 0.8478, a: 0.0255, b: -0.0514, color: ColorLevel3.VeryPaleViolet },
  { l: 0.6748, a: 0.0252, b: -0.0489, color: ColorLevel3.PaleViolet },
  { l: 0.4486, a: 0.0265, b: -0.0528, color: ColorLevel3.GrayishViolet },
  { l: 0.5929, a: 0.1857, b: -0.1566, color: ColorLevel3.VividPurple },
  { l: 0.7367, a: 0.1038, b: -0.0943, color: ColorLevel3.BrilliantPurple },
  { l: 0.5494, a: 0.1068, b: -0.0982, color: ColorLevel3.StrongPurple },
  { l: 0.3931, a: 0.1098, b: -0.0977, color: ColorLevel3.DeepPurple },
  { l: 0.2963, a: 0.0965, b: -0.0862, color: ColorLevel3.VeryDeepPurple },
  { l: 0.8423, a: 0.0672, b: -0.0621, color: ColorLevel3.VeryLightPurple },
  { l: 0.7209, a: 0.0669, b: -0.0639, color: ColorLevel3.LightPurple },
  { l: 0.5464, a: 0.0704, b: -0.0663, color: ColorLevel3.ModeratePurple },
  { l: 0.3915, a: 0.0575, b: -0.0553, color: ColorLevel3.DarkPurple },
  { l: 0.2794, a: 0.0546, b: -0.0517, color: ColorLevel3.VeryDarkPurple },
  { l: 0.8692, a: 0.0341, b: -0.0351, color: ColorLevel3.VeryPalePurple },
  { l: 0.7049, a: 0.0356, b: -0.031, color: ColorLevel3.PalePurple },
  { l: 0.5389, a: 0.0352, b: -0.0274, color: ColorLevel3.GrayishPurple },
  { l: 0.3937, a: 0.0316, b: -0.0211, color: ColorLevel3.DarkGrayishPurple },
  { l: 0.2738, a: 0.0258, b: -0.0202, color: ColorLevel3.BlackishPurple },
  { l: 0.9179, a: 0.0185, b: -0.0168, color: ColorLevel3.PurplishWhite },
  { l: 0.7939, a: 0.0188, b: -0.0161, color: ColorLevel3.LightPurplishGray },
  { l: 0.6269, a: 0.0176, b: -0.0131, color: ColorLevel3.PurplishGray },
  { l: 0.4526, a: 0.0178, b: -0.0146, color: ColorLevel3.DarkPurplishGray },
  { l: 0.2783, a: 0.0119, b: -0.0154, color: ColorLevel3.PurplishBlack },
  { l: 0.6085, a: 0.2237, b: -0.1002, color: ColorLevel3.VividReddishPurple },
  { l: 0.5526, a: 0.1402, b: -0.0627, color: ColorLevel3.StrongReddishPurple },
  { l: 0.4038, a: 0.1388, b: -0.0676, color: ColorLevel3.DeepReddishPurple },
  { l: 0.3032, a: 0.1099, b: -0.0596, color: ColorLevel3.VeryDeepReddishPurple },
  { l: 0.6764, a: 0.0884, b: -0.0394, color: ColorLevel3.LightReddishPurple },
  { l: 0.5473, a: 0.0947, b: -0.0427, color: ColorLevel3.ModerateReddishPurple },
  { l: 0.3926, a: 0.0721, b: -0.0364, color: ColorLevel3.DarkReddishPurple },
  { l: 0.2834, a: 0.0702, b: -0.0398, color: ColorLevel3.VeryDarkReddishPurple },
  { l: 0.6728, a: 0.0525, b: -0.0255, color: ColorLevel3.PaleReddishPurple },
  { l: 0.5426, a: 0.0554, b: -0.0264, color: ColorLevel3.GrayishReddishPurple },
  { l: 0.8213, a: 0.1258, b: -0.0569, color: ColorLevel3.BrilliantPurplishPink },
  { l: 0.757, a: 0.1543, b: -0.0505, color: ColorLevel3.StrongPurplishPink },
  { l: 0.6831, a: 0.1593, b: -0.0358, color: ColorLevel3.DeepPurplishPink },
  { l: 0.8379, a: 0.0889, b: -0.0289, color: ColorLevel3.LightPurplishPink },
  { l: 0.7599, a: 0.094, b: -0.0249, color: ColorLevel3.ModeratePurplishPink },
  { l: 0.6755, a: 0.0979, b: -0.0134, color: ColorLevel3.DarkPurplishPink },
  { l: 0.8693, a: 0.0462, b: -0.0179, color: ColorLevel3.PalePurplishPink },
  { l: 0.7544, a: 0.0488, b: -0.0166, color: ColorLevel3.GrayishPurplishPink },
  { l: 0.5986, a: 0.2272, b: -0.0223, color: ColorLevel3.VividPurplishRed },
  { l: 0.544, a: 0.1728, b: -0.012, color: ColorLevel3.StrongPurplishRed },
  { l: 0.4186, a: 0.1605, b: -0.0212, color: ColorLevel3.DeepPurplishRed },
  { l: 0.3022, a: 0.1165, b: -0.0316, color: ColorLevel3.VeryDeepPurplishRed },
  { l: 0.5482, a: 0.133, b: -0.0101, color: ColorLevel3.ModeratePurplishRed },
  { l: 0.3924, a: 0.105, b: -0.0156, color: ColorLevel3.DarkPurplishRed },
  { l: 0.2788, a: 0.0795, b: -0.022, color: ColorLevel3.VeryDarkPurplishRed },
  { l: 0.6707, a: 0.0579, b: -0.011, color: ColorLevel3.LightGrayishPurplishRed },
  { l: 0.5438, a: 0.0787, b: -0.0085, color: ColorLevel3.GrayishPurplishRed },
  { l: 0.9168, a: 0.0092, b: -0.0084, color: ColorLevel3.White },
  { l: 0.7867, a: 0.0096, b: -0.0087, color: ColorLevel3.LightGray },
  { l: 0.6202, a: 0.009, b: -0.005, color: ColorLevel3.MediumGray },
  { l: 0.451, a: 0.0068, b: -0.0046, color: ColorLevel3.DarkGray },
  { l: 0.2838, a: 0.0038, b: -0.0026, color: ColorLevel3.Black },
])

/** @param {keyof typeof ColorLevel1} x */
export let getColorLevel1 = x => ColorLevel1[x]

/** @param {keyof typeof ColorLevel2} x */
export let getColorLevel2 = x => ColorLevel2[x]

/** @param {keyof typeof ColorLevel3} x */
export let getColorLevel3 = x => ColorLevel3[x]

/** @param {keyof typeof ColorLevel2Parent} x */
export let getColorLevel2Parent = x => ColorLevel2Parent[x]

/** @param {keyof typeof ColorLevel3Parent} x */
export let getColorLevel3Parent = x => ColorLevel3Parent[x]

/**
 * @param {{ l: number, a: number, b: number }} x
 * @param {{ l: number, a: number, b: number }} y
 */
export let colorDistance = (x, y) => Math.hypot(x.l - y.l, x.a - y.a, x.b - y.b)

/** @param {{ l: number, a: number, b: number }} color */
export let findColorCentroid = color =>
  ColorCentroid
    .toSorted((x, y) => colorDistance(color, x) - colorDistance(color, y))
    .at(0)
